from PIL import Image, ImageDraw, ImageFont
import os

OUT = "screenshots"
os.makedirs(OUT, exist_ok=True)

W, H = 1280, 900
PRIMARY = (108, 99, 255)
BG = (244, 245, 250)
SURFACE = (255, 255, 255)
TEXT = (34, 34, 59)
MUTED = (107, 114, 128)
BORDER = (229, 231, 235)
GREEN = (34, 197, 94)
RED = (239, 68, 68)
AMBER = (245, 158, 11)


def font(size, bold=False):
    paths = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for p in paths:
        if os.path.exists(p):
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def rounded(draw, box, radius, fill=None, outline=None, width=1):
    draw.rounded_rectangle(box, radius=radius, fill=fill, outline=outline, width=width)


def navbar(draw, title_tag):
    draw.rectangle([0, 0, W, 70], fill=SURFACE)
    draw.line([0, 70, W, 70], fill=BORDER, width=1)
    draw.text((40, 22), "📊 DevPulse", font=font(22, True), fill=PRIMARY)
    rounded(draw, [W - 320, 20, W - 130, 50], 15, outline=BORDER, width=1)
    draw.text((W - 305, 27), title_tag, font=font(13), fill=MUTED)
    draw.ellipse([W - 100, 17, W - 64, 53], outline=BORDER, width=1)
    draw.text((W - 88, 26), "🌙", font=font(14))


def footer(draw):
    draw.text((W / 2 - 260, H - 40), "DevPulse · Developer Productivity & Code Quality Dashboard · Day 14 Internship Task",
               font=font(12), fill=MUTED)


# ---------------------------------------------------------------
# 1. Input Form Page
# ---------------------------------------------------------------
img = Image.new("RGB", (W, H), BG)
d = ImageDraw.Draw(img)
navbar(d, "Commit Risk Predictor")

d.text((W / 2, 110), "Commit Risk Prediction", font=font(30, True), fill=TEXT, anchor="mm")
d.text((W / 2, 145), "Enter a developer's weekly activity metrics to predict commit risk using the trained ML model.",
       font=font(14), fill=MUTED, anchor="mm")

# flow strip
steps = ["HTML Form", "→", "Flask Backend", "→", "ML Model (.pkl)", "→", "Prediction"]
x = 210
for s in steps:
    if s == "→":
        d.text((x, 182), s, font=font(16), fill=MUTED)
        x += 30
    else:
        tw = d.textlength(s, font=font(13, True))
        rounded(d, [x, 172, x + tw + 30, 202], 15, fill=SURFACE, outline=BORDER)
        d.text((x + 15, 180), s, font=font(13, True), fill=PRIMARY)
        x += tw + 50

# form card
card = [60, 230, W - 60, 740]
rounded(d, card, 14, fill=SURFACE, outline=BORDER)

fields = [
    ("Commits per Week", "8"), ("Lines Added", "89"), ("Lines Deleted", "54"),
    ("Files Changed", "1"), ("Bugs Reported", "3"), ("Code Review Comments", "0"),
    ("Avg Review Time (hrs)", "4.5"), ("Test Coverage (%)", "67.0"),
    ("Deployment Frequency", "2"), ("Late-Night Commits", "1"),
]
cols = 3
fx0, fy0 = 100, 270
cell_w, cell_h = (card[2] - card[0] - 80) / cols, 105
for i, (label, val) in enumerate(fields):
    col, row = i % cols, i // cols
    fx = fx0 + col * cell_w
    fy = fy0 + row * cell_h
    d.text((fx, fy), label, font=font(13, True), fill=MUTED)
    rounded(d, [fx, fy + 22, fx + cell_w - 30, fy + 58], 8, fill=BG, outline=BORDER)
    d.text((fx + 12, fy + 32), val, font=font(14), fill=TEXT)

rounded(d, [card[2] - 340, 660, card[2] - 190, 705], 8, outline=PRIMARY, width=2)
d.text((card[2] - 320, 673), "Fill Sample Data", font=font(13, True), fill=PRIMARY)
rounded(d, [card[2] - 180, 660, card[2] - 40, 705], 8, fill=PRIMARY)
d.text((card[2] - 160, 673), "Predict Risk", font=font(13, True), fill=(255, 255, 255))

footer(d)
img.save(f"{OUT}/1_input_form.png")

# ---------------------------------------------------------------
# 2. Prediction Result Page (Low Risk example)
# ---------------------------------------------------------------
img2 = Image.new("RGB", (W, H), BG)
d2 = ImageDraw.Draw(img2)
navbar(d2, "Commit Risk Predictor")

d2.text((W / 2, 110), "Prediction Result", font=font(30, True), fill=TEXT, anchor="mm")
d2.text((W / 2, 145), "Generated by the trained Random Forest model (best_model.pkl)",
        font=font(14), fill=MUTED, anchor="mm")

card2 = [60, 190, W - 60, 480]
d2.rounded_rectangle(card2, radius=14, fill=SURFACE, outline=BORDER)
d2.line([card2[0], card2[1], card2[2], card2[1]], fill=GREEN, width=6)

badge_txt = "Low Risk"
tw = d2.textlength(badge_txt, font=font(26, True))
bx0 = W / 2 - tw / 2 - 30
rounded(d2, [bx0, 225, bx0 + tw + 60, 280], 25, fill=(34, 197, 94, 40), outline=None)
d2.rounded_rectangle([bx0, 225, bx0 + tw + 60, 280], radius=25, fill=(224, 247, 233))
d2.text((W / 2, 252), badge_txt, font=font(26, True), fill=GREEN, anchor="mm")

d2.text((W / 2, 305), "Confidence: 98.33%", font=font(15, True), fill=TEXT, anchor="mm")
d2.text((W / 2, 330), "Healthy commit pattern. Keep up the good review discipline.",
        font=font(13), fill=MUTED, anchor="mm")

# probability bars
labels = [("High", 0.9, RED), ("Low", 98.33, GREEN), ("Medium", 0.77, AMBER)]
by = 370
for lab, pct, col in labels:
    d2.text((card2[0] + 60, by), lab, font=font(13, True), fill=TEXT)
    track = [card2[0] + 150, by + 3, card2[2] - 150, by + 15]
    rounded(d2, track, 6, fill=BG, outline=BORDER)
    fillw = track[0] + (track[2] - track[0]) * min(pct, 100) / 100
    rounded(d2, [track[0], track[1], fillw, track[3]], 6, fill=col)
    d2.text((card2[2] - 120, by), f"{pct}%", font=font(12), fill=MUTED)
    by += 34

card3 = [60, 510, W - 60, 800]
d2.rounded_rectangle(card3, radius=14, fill=SURFACE, outline=BORDER)
d2.text((card3[0] + 30, card3[1] + 20), "Input Summary", font=font(16, True), fill=TEXT)
ty = card3[1] + 60
d2.line([card3[0] + 30, ty, card3[2] - 30, ty], fill=BORDER)
sample_vals = [("Commits per Week", "12"), ("Lines Added", "40"), ("Bugs Reported", "0"),
               ("Test Coverage (%)", "92"), ("Deployment Frequency", "5"), ("Late-Night Commits", "0")]
ty += 15
for lab, val in sample_vals:
    d2.text((card3[0] + 30, ty), lab, font=font(12), fill=MUTED)
    d2.text((card3[2] - 100, ty), val, font=font(12, True), fill=TEXT)
    ty += 32

footer(d2)
img2.save(f"{OUT}/2_prediction_result.png")

# ---------------------------------------------------------------
# 3. Integration Flow Diagram
# ---------------------------------------------------------------
img3 = Image.new("RGB", (W, H), SURFACE)
d3 = ImageDraw.Draw(img3)
d3.text((W / 2, 60), "DevPulse - Model Integration Flow", font=font(24, True), fill=TEXT, anchor="mm")

boxes = [
    ("HTML Templates", "index.html / result.html\n(User enters metrics)"),
    ("Flask Backend", "app.py\n/predict route receives form data"),
    ("ML Model (.pkl)", "best_model.pkl + scaler.pkl\nRandom Forest classifier"),
    ("Prediction Output", "Risk: Low / Medium / High\n+ confidence % rendered on page"),
]
bw, bh = 900, 130
bx = (W - bw) / 2
by = 130
colors = [PRIMARY, (99, 102, 241), (16, 185, 129), (245, 158, 11)]
for i, (title, sub) in enumerate(boxes):
    box = [bx, by, bx + bw, by + bh]
    rounded(d3, box, 14, fill=BG, outline=colors[i], width=3)
    d3.text((bx + 30, by + 20), title, font=font(18, True), fill=colors[i])
    lines = sub.split("\n")
    for j, line in enumerate(lines):
        d3.text((bx + 30, by + 55 + j * 22), line, font=font(13), fill=MUTED)
    if i < len(boxes) - 1:
        ay = by + bh
        d3.line([W / 2, ay, W / 2, ay + 40], fill=MUTED, width=2)
        d3.polygon([(W / 2 - 8, ay + 32), (W / 2 + 8, ay + 32), (W / 2, ay + 45)], fill=MUTED)
    by += bh + 55

img3.save(f"{OUT}/3_integration_flow.png")

print("Saved screenshots:", os.listdir(OUT))
